### PR TITLE
Week05 fixed input on bottom, display messages from the bottom of screen, removed always displayed scrollbar

### LINKED ISSUE #123: Some browsers display scrollbars  when app is opened.

### PR DESCRIPTION
**Pull request by viniciuspietscher**
Closes #123 

- Fixed the input field in the bottom of the screen;
- add container to use 100% of vh;
- display messages from the bottom first;
- order messages by timestamp 'desc';
- bottom bar is responsive and will shrink in size on smaller screens;

https://user-images.githubusercontent.com/8095975/186951723-116e18f7-e05b-41ad-a81d-6f9c79bce941.mp4

We still have a problem where once we have enough messages to fill the screen it will not automatically scroll down.

https://user-images.githubusercontent.com/8095975/186951951-0f6e9837-57e0-42b7-8278-3892633ced51.mp4

### CODE REVIEW

File: src/components/BottomInputComponent.js [hunk 1]
```diff
@@ -50,31 +52,63 @@ function BottomInputComponent({ currentUser, isFocused }) {
...
+    //       onClick={handleSubmitMessage}
+    //       style={{
+    //         color: "#3BBF69",
+    //         fontSize: "44px",
+    //         backgroundColor: "#1A2930",
+    //         borderRadius: "10px",
+    //       }}
+    //     />
+    //   </form>
+    // </>
```
Comment (viniciuspietscher) [inline src/components/BottomInputComponent.js:111]:
```suggestion
```
