### PR TITLE
Week05 - Bug fix - show login button if user won't sign in

### LINKED ISSUE #103: Bug: Show Google Login button if user closes Sign In popup without logging in.
If the user closes the popup window without signing in, the `isLoading` state is never changed back to false, keeping the spinner in the screen until the user refreshes the page.

### PR DESCRIPTION
**Pull request by viniciuspietscher**
Closes #103 

When user closes sign in popup without authenticating set the isloading state back to false and shows the google login button again.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -12,8 +12,8 @@ function App() {
     setAuthState(auth)
   }
 
-  const handleIsLoadingStateChange = (isLoading) => {
-    setIsLoading(!isLoading)
+  const handleIsLoadingStateChange = (bool) => {
+    bool ? setIsLoading(bool) : setIsLoading(false)
```
Comment (viniciuspietscher) [inline src/App.js:16]:
```suggestion
    bool ? setIsLoading(true) : setIsLoading(false)
```
